name: PHPUnit and End-to-End Tests

on:
    pull_request:
    push:
        branches:
            - ci/e2e-test
            - ci/automated-testing

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    test:
        name: phpunit and e2e tests
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false

        steps:
            - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

            - name: Use desired version of NodeJS
              uses: actions/setup-node@38d90ce44d5275ad62cc48384b3d8a58c500bb5f # v2.2.2
              with:
                  node-version: 14
                  cache: npm

            - name: Npm install and build
              run: |
                  npm ci
                  npm run build
                  grunt

            - name: Composer install and build
              run: |
                  composer install

            - name: Setup WordPress
              run: |
                  npm run env:start

            - name: Running the phpunit tests
              run: |
                  npm run test:phpunit

            - name: Running the e2e tests
              uses: nick-fields/retry@v2
              with:
                timeout_seconds: 15
                max_attempts: 3
                retry_on: error
                command: npm run test:e2e

            - name: Archive debug artifacts (screenshots, HTML snapshots)
              uses: actions/upload-artifact@e448a9b857ee2131e752b06002bf0e093c65e571 # v2.2.2
              if: always()
              with:
                  name: failures-artifacts
                  path: artifacts
                  if-no-files-found: ignore

            - name: Archive flaky tests report
              uses: actions/upload-artifact@e448a9b857ee2131e752b06002bf0e093c65e571 # v2.2.2
              if: always()
              with:
                  name: flaky-tests-report
                  path: flaky-tests
                  if-no-files-found: ignore
